all:out
out:server.c server2.c server3.c client.c client2.c client3.c
	gcc server.c -o server.out
	gcc server2.c -o server2.out
	gcc client.c -o client.out
	gcc client2.c -o client2.out
	gcc server3.c -o server3.out
	gcc client3.c -o client3.out
